output   = "appdb"
pkgname  = "appdb"
add-global-variants = true
wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "postgres"
host   = "localhost"
port   = 60001
user   = "postgres"
pass   = "secret"
schema = "template"
sslmode = "disable"

[[types]]
[types.match]
type = "null.Int"
nullable = true

[types.replace]
type = "null.Int32"

[[types]]
[types.match]
type = "int"

[types.replace]
type = "int32"
